# NeON Build File (http://github.com/c4s4/neon)

doc: Project for my parent build files

extends: _git_master

targets:

  version:
    doc: Generate release version
    steps:
    - 'VERSION = replace(replace(now()[0:16], " ", "="), ":", "-")'
    - print: 'Setting VERSION to "={VERSION}"'

  clean:
    doc: Clean generated files
    steps:
    - delete: 'rust/target'
    - delete: 'rust/Cargo.lock'
