# NeON Build File (http://github.com/c4s4/neon)

doc: Project for my parent build files

extends:
- ./git-master.yml

properties:
  VERSION: 'UNKNOWN'

targets:

  version:
    doc: Generate release version
    steps:
    - 'VERSION = replace(replace(now()[0:16], " ", "="), ":", "-")'
