# NeON Build File (http://github.com/c4s4/neon)

default: [lint, test]

extends:
- c4s4/build/python.yml

environment:
  FLASK_APP: '={NAME}.py'

targets:

  run:
    doc: Run flask server
    steps:
    - $: ['={VENV_DIR}/bin/flask', 'run']

  test:
    doc: Run flask tests
    steps:
    - $: ['={VENV_DIR}/bin/pytest']
